name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: apt update && apt -y install cmake
    - name: build
      run: Generator/bin/build
      
  format:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: apt update && apt -y install clang-format
    - name: format
      run: Generator/bin/format
    
  lint:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: apt update && apt -y install shellcheck
    - name: format
      run: Generator/bin/lint
    
