name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #Build
      - name: configure
        working-directory: ./generator
        run: bin/setup
      - name: build
        working-directory: ./generator
        run: bin/build
      #Format
      - name: configure
        run: sudo apt-get -y install clang-format
      - name: format
        working-directory: ./generator
        run: bin/format
      #Lint
      - name: configure
        run: sudo apt-get -y install shellcheck
      - name: lint
        working-directory: ./generator
        run: bin/lint
